#!/bin/sh

MHz=`grep 'MHz' /proc/cpuinfo | cut -c11- |sed -n '1p'`
[ -z "$MHz" ] && MHz=`echo "$(cat /sys/devices/system/cpu/cpu[04]/cpufreq/cpuinfo_cur_freq)/1000" | bc`
TEMP=`sensors 2>/dev/null | grep 'Core 0' | cut -c12-`
[ -z "$TEMP" ] && TEMP=`echo "scale=2; $(cat /sys/class/thermal/thermal_zone0/temp)/1000" | bc`°
echo "$MHz MHz $TEMP "
